version: '3.8'

services:
  postgres_db:
    build:
      context: db/postgres
      dockerfile: Dockerfile
    container_name: nest_gql_postgres_database
    environment:
      POSTGRES_USER: user_nest_gql
      POSTGRES_PASSWORD: password_nest_gql
      POSTGRES_DB: database_nest_gql
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - dev_nest_gql_network

networks:
  dev_nest_gql_network: {}

volumes:
  postgres-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./db/data/postgres